#INCLUDE "PROTHEUS.CH"
#INCLUDE "Rwmake.CH"
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑฺฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฟฑฑ
ฑฑณFun…o    ณ REST003  ณ Autor ณ 	Robson Bueno         ณ Data ณ 18.04.07 ณฑฑ
ฑฑรฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤมฤฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤมฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤฤดฑฑ
ฑฑณDescri…o ณ Aprovacao de requisicao ao almoxarifado                     ณฑฑ
ฑฑณ          ณ                                                             ณฑฑ
ฑฑรฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤดฑฑ
ฑฑณUso       ณ REST003                                                     ณฑฑ
ฑฑรฤฤฤฤฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤดฑฑ
ฑฑณ ATUALIZACOES SOFRIDAS DESDE A CONSTRUCAO INICIAL.                      ณฑฑ
ฑฑรฤฤฤฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤยฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤดฑฑ
ฑฑณ PROGRAMADOR  ณ DATA   ณ BOPS ณ  MOTIVO DA ALTERACAO                    ณฑฑ
ฑฑรฤฤฤฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤลฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤดฑฑ
ฑฑณXXXXXXXXXXXXXXณXX/XX/XXณXXXXXXณ                                         ณฑฑ
ฑฑภฤฤฤฤฤฤฤฤฤฤฤฤฤฤมฤฤฤฤฤฤฤฤมฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤูฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
User Function RESTA003()
//ฺฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ
//ณ Define Variaveis                                     ณ
//ภฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤู
Local aCores    := {},aCampos:={}

aCores    := {{	'CP_STATSA=="B"  .AND. CP_PREREQU==" "'	 , 'BR_PRETO'},;		// SA BLOQUEADA
			   {'CP_STATSA==" " .AND. CP_PREREQU==" "'	 , 'BR_VERDE'},;       // SA APROVADA
			   {'CP_STATSA==" " .AND. CP_PREREQU=="S"' , 'BR_VERMELHO'}}     // SA REQUISITADA	

PRIVATE aRotina := { { "Pesquisar","AxPesqui"  ,0,1},;             // Pesquisa  SA
						   { "Visualizar","AxVisual",0,2},;        //  Vizualiza SA
                     { OemToAnsi("Aprova็ใo"),"U_Raprsa",0,3},;    // Aprova SA Bloqueada
					 { OemToAnsi("Canc. Aprov."),"U_Raprsa",0,4},; // Cancela Bloqueio
					    	{ "Legenda","U_RLest001",0,5} }  
						
//ฺฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ
//ณ Define o cabecalho da tela de atualizacoes           ณ
//ภฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤู
PRIVATE cCadastro := OemToAnsi("Aprova็ใo de S.A.")

//ฺฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ
//ณ Endereca a funcao de BROWSE                          ณ
//ภฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤู 
aCampos := {{"Solicitante","CP_SOLICIT"},{"Emissao","CP_EMISSAO"},{"Nr.S.A.","CP_NUM"},{"Item S.A.","CP_ITEM"},{"Produto","CP_PRODUTO"},{"Descricao","CP_DESCRI"},{"Quantidade","CP_QUANT"}}
mBrowse(6,1,22,75,"SCP",aCampos,,,,3,aCores)

Return(.T.)

                  
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณRAPRSA    บAutor  ณRobson Bueno        บ Data ณ 18/04/2007  บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณTela para confirmacao da acao acionada na rotina            บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณHCI                                                         บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
User Function RAPRSA(cAlias,nReg,nOpcX)

Local oDlgl
// VERIFICA SE O APROVADOR PODE LIBERAR REQUISICAO
IF VERAPROV(SCP->CP_SOLICIT)
//VERIFICA SE JA FOI GERADA PRE REQUISICAO
IF SCP->CP_PREREQU=="S" 
    Aviso("Observacao","Nao e possivel alterar situacao de SA ja requisitada !!!",{"Ok"},,"Atencao:")
ELSE
IF nOpcX==3
  IF SCP->CP_STATSA=="B"
		
    @ 000,000 To 220,400 Dialog Odlg1 Title OemToAnsi("	Libera็ใo de S.A.")
    @ 003,008 To 110,200 Title OemToAnsi("Aprova Solicita็ใo ao Armazem?")
   
    @ 015,015 Say OemToAnsi("N.Requis:") OF Odlgl PIXEL
    @ 015,045 Say SCP->CP_Num Picture "@!" SIZE 60,10 OF Odlgl PIXEL
    @ 025,015 Say OemToAnsi("Produto:") OF Odlgl PIXEL
    @ 025,045 Say SCP->CP_PRODUTO Picture "@!" SIZE 60,10 OF Odlgl PIXEL
    @ 035,015 Say OemToAnsi("Descri็ใo:")OF Odlgl PIXEL
    @ 035,045 Say SCP->CP_DESCRI Picture "@!" SIZE 160,10 OF Odlgl PIXEL
    @ 045,015 Say OemToAnsi("Qtd:") OF Odlgl PIXEL
    @ 045,045 Say SCP->CP_QUANT Picture "@!" SIZE 40,10 OF Odlgl PIXEL
    @ 055,015 Say OemToAnsi("Emitente:")OF Odlgl PIXEL
    @ 055,045 Say SCP->cp_solicit Picture "@!" SIZE 80,10 OF Odlgl PIXEL
    @ 090,030 BMPBUTTON TYPE 1 ACTION OkProc(odlg1)
    @ 090,060 BMPBUTTON TYPE 2 ACTION Finaliza(odlg1)

    Activate Dialog Odlg1 CENTER
  ELSE
    Aviso("Observacao","Requisicao ja foi aprovada !!!",{"Ok"},,"Atencao:")
  ENDIF
ELSEIF nOpcX==4
  IF SCP->CP_STATSA==" "
   		
    @ 000,000 To 220,400 Dialog Odlg1 Title OemToAnsi("Bloqueio de S.A.")
    @ 003,008 To 110,200 Title OemToAnsi("Cancela Libera็ใo?")
   
    @ 015,015 Say OemToAnsi("N.Requis:") OF Odlgl PIXEL
    @ 015,045 Say SCP->CP_Num Picture "@!" SIZE 60,10 OF Odlgl PIXEL
    @ 025,015 Say OemToAnsi("Produto:") OF Odlgl PIXEL
    @ 025,045 Say SCP->CP_PRODUTO Picture "@!" SIZE 60,10 OF Odlgl PIXEL
    @ 035,015 Say OemToAnsi("Descri็ใo:")OF Odlgl PIXEL
    @ 035,045 Say SCP->CP_DESCRI Picture "@!" SIZE 160,10 OF Odlgl PIXEL
    @ 045,015 Say OemToAnsi("Qtd:") OF Odlgl PIXEL
    @ 045,045 Say SCP->CP_QUANT Picture "@!" SIZE 40,10 OF Odlgl PIXEL
    @ 055,015 Say OemToAnsi("Emitente:")OF Odlgl PIXEL
    @ 055,045 Say SCP->cp_solicit Picture "@!" SIZE 80,10 OF Odlgl PIXEL
    @ 090,030 BMPBUTTON TYPE 1 ACTION OkProc(odlg1)
    @ 090,060 BMPBUTTON TYPE 2 ACTION Finaliza(odlg1)

    Activate Dialog Odlg1 CENTER
  ELSE
    Aviso("Observacao","Requisicao ja esta bloqueada !!!",{"Ok"},,"Atencao:")
  Endif
ENDIF
ENDIF
ENDIF
Return(.T.)

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณOkProc    บAutor  ณRobson Bueno        บ Data ณ 18/04/2007  บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณProcessamento no banco de dados da acao solicitada e confir บฑฑ
ฑฑบ          ณmada                                                        บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณHCI                                                         บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Static Function OkProc(odlg1)
Local cAliasSCP := GetArea()
IF SCP->CP_STATSA=="B"
  RecLock("SCP",.F.)
  SCP->CP_STATSA:=""
  SCP->CP_XAPROVA:=Substr(cUsuario,7,15)
  MsUnLock()
ELSE
  RecLock("SCP",.F.)
  SCP->CP_STATSA:="B"
  SCP->CP_XAPROVA:=""
  MsUnLock()
ENDIF
Close(Odlg1)
RestArea(cAliasSCP)
Return

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณFinaliza  บAutor  ณRobson Bueno        บ Data ณ 18/04/2007  บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณFinalizacao do Objeto                                       บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณHCI                                                         บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Static Function Finaliza(Odlg1)

Aviso("Observacao","A็ใo Cancelada Pelo Usuario !!!",{"Ok"},,"Atencao:")

Close(Odlg1)

Return
                 
User Function RLest001()

BrwLegenda(cCadastro,"Situacoes",{{"BR_PRETO","Requisicao Nao Aprovada"}, {"BR_VERDE","Requisicao Aprovada"},;  
                                  {"BR_VERMELHO","Gerado Pre-Requisicao "}})

Return (.T.)


/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณVerAprov  บAutor  ณRobson Bueno        บ Data ณ 18/04/2007  บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณFinalizacao do Objeto                                       บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณHCI                                                         บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
Static Function VerAprov(cReq)
Local aAreaAtu	:= GetArea()												// Salva a area atual
Local lRet		:= .T.														// Inicializa o retorno
DbSelectArea("SZC")
dbSetOrder(1)
  If !MsSeek(xFilial("SZC")+SUBSTRING(cReq,1,15)+SUBSTR(cUSERNAME,1,15))
    Aviso("Observacao","Voce Nao pode Aprovar Requisicoes deste Usuario",{"Ok"},,"Atencao:")
    lRet=.F.
  ENDIF
// Restaura a integridade dos dados

RestArea(aAreaAtu)


Return (lRet)
                 
