
GO
/****** Object:  StoredProcedure [dbo].[sp_mov_gestoq_alt]    Script Date: 15/02/2021 16:48:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER Procedure [dbo].[sp_mov_gestoq_alt]( 
	@PRODUTO		AS VARCHAR(15)	,
	@QTD			AS FLOAT			,
	@VLR_UN			AS FLOAT		,
	@DOC			AS INT			,
	@CGC_EMP		AS VARCHAR(18)	,
	@ID_FORNEC		AS INT			,
	@DATA			AS DATETIME		,
	@AMBPROD		AS SMALLINT		,
	@ID_MOV_MAT		AS INT			,
	@D1_LOTEFOR		AS VARCHAR(18)  ,
	@ROWCOUNT		AS INT out
)
As
Begin
	declare @ID_EMPRESA  AS INT
	declare @ID_MATERIAL AS INT

--ABRE TRANSAÇÃO
BEGIN TRAN

	IF @AMBPROD = 1
	BEGIN
		print 'AMBIENTE DE PRODUCAO'

		--PEGA O ID DO MATERIAL
		SELECT @ID_MATERIAL = ID_MATERIAL
		FROM TPCP..MATERIAL
		WHERE CODIGO = @PRODUTO

		PRINT 'ID_MATERIAL = '+CONVERT(VARCHAR(100), @ID_MATERIAL)

		--PEGA O ID DA EMPRESA
		select @ID_EMPRESA = ID_EMPRESA 
		from TPCP..EMPRESA
		WHERE REPLACE(REPLACE(REPLACE(REPLACE(CGC, '.', ''), '/', ''), '/', ''), '-', '')  = @CGC_EMP

		PRINT 'ID_EMPRESA = '+CONVERT(VARCHAR(100), @ID_EMPRESA)

		-- INSERE O MOVIMENTO
		UPDATE TPCP..MOV_MAT
		SET ID_MATERIAL = @ID_MATERIAL, 
			DATA		= @DATA, 
			QTD			= @QTD, 
			VLR_UN		= @VLR_UN, 
			DOC			= @DOC, 
			ID_EMPRESA	= @ID_EMPRESA, 
			ID_FORNEC	= @ID_FORNEC,
			LOTE		= @D1_LOTEFOR
		WHERE ID_MOV_MAT = @ID_MOV_MAT

		Set @ROWCOUNT = @@ROWCOUNT
	END
	ELSE
	BEGIN
		print 'AMBIENTE DE PRODUCAO'

		--PEGA O ID DO MATERIAL
		SELECT @ID_MATERIAL = ID_MATERIAL
		FROM TESTE..MATERIAL
		WHERE CODIGO = @PRODUTO

		PRINT 'ID_MATERIAL = '+CONVERT(VARCHAR(100), @ID_MATERIAL)

		--PEGA O ID DA EMPRESA
		select @ID_EMPRESA = ID_EMPRESA 
		from TESTE..EMPRESA
		WHERE REPLACE(REPLACE(REPLACE(REPLACE(CGC, '.', ''), '/', ''), '/', ''), '-', '')  = @CGC_EMP

		PRINT 'ID_EMPRESA = '+CONVERT(VARCHAR(100), @ID_EMPRESA)

		-- INSERE O MOVIMENTO
		UPDATE TESTE..MOV_MAT
		SET ID_MATERIAL = @ID_MATERIAL, 
			DATA		= @DATA, 
			QTD			= @QTD, 
			VLR_UN		= @VLR_UN, 
			DOC			= @DOC, 
			ID_EMPRESA	= @ID_EMPRESA, 
			ID_FORNEC	= @ID_FORNEC,
			LOTE		= @D1_LOTEFOR
		WHERE ID_MOV_MAT = @ID_MOV_MAT	
		
		Set @ROWCOUNT = @@ROWCOUNT
	END

-- CONFIRMA TRANSAÇÃO
COMMIT

END