
GO
/****** Object:  StoredProcedure [dbo].[sp_mov_gestoq]    Script Date: 15/02/2021 16:48:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[sp_mov_gestoq]( 
	@PRODUTO		AS VARCHAR(15)	,
	@QTD			AS FLOAT		,
	@VLR_UN			AS FLOAT		,
	@DOC			AS INT			,
	@CGC_EMP		AS VARCHAR(18)	,
	@ID_FORNEC		AS INT			,
	@DATA			AS DATETIME		,
	@AMBPROD		AS INT			,
	@ID_NOTA_COMPRA	AS INT          ,
	@D1_LOTEFOR		AS VARCHAR(18)  ,
	@ID_MOV_MAT		AS INT OUT

)
As
Begin
	declare @ID_EMPRESA  AS INT
	declare @ID_MATERIAL AS INT
	
	BEGIN TRAN

		IF @AMBPROD = 1
		BEGIN
			print 'AMBIENTE DE PRODUCAO'

			--PEGA O ID DO MATERIAL
			SELECT @ID_MATERIAL = ID_MATERIAL
			FROM TPCP..MATERIAL
			WHERE CODIGO = @PRODUTO

			PRINT 'ID_MATERIAL = '+CONVERT(VARCHAR(100), @ID_MATERIAL)

			--PEGA O ID DA EMPRESA
			select @ID_EMPRESA = ID_EMPRESA 
			from TPCP..EMPRESA
			WHERE REPLACE(REPLACE(REPLACE(REPLACE(CGC, '.', ''), '/', ''), '/', ''), '-', '')  = @CGC_EMP
			AND   ID_EMPRESA <> 999

			PRINT 'ID_EMPRESA = '+CONVERT(VARCHAR(100), @ID_EMPRESA)

			--PEGA O PROXIMO ID
			select @ID_MOV_MAT = max(ID_MOV_MAT)+1 
			from TPCP..MOV_MAT

			PRINT 'ID_MOV_MAT = '+CONVERT(VARCHAR(100), @ID_MOV_MAT)

			-- INSERE O MOVIMENTO
			insert into TPCP..MOV_MAT
			  (ID_MOV_MAT, ID_MATERIAL, DATA, QTD, TP_MOV, VLR_UN, DOC, MOVIMENTO, ID_EMPRESA, ID_FORNEC, LOTE, ID_NOTA_COMPRA)
			values
			  (@ID_MOV_MAT, @ID_MATERIAL, @DATA, @QTD, 35, @VLR_UN, @DOC, 1, @ID_EMPRESA, @ID_FORNEC, @D1_LOTEFOR, @ID_NOTA_COMPRA)
		END
		ELSE
		BEGIN
			print 'AMBIENTE DE TESTES'

			--PEGA O ID DO MATERIAL
			SELECT @ID_MATERIAL = ID_MATERIAL
			FROM TPCP..MATERIAL
			WHERE CODIGO = @PRODUTO

			PRINT 'ID_MATERIAL = '+CONVERT(VARCHAR(100), @ID_MATERIAL)

			--PEGA O ID DA EMPRESA
			select @ID_EMPRESA = ID_EMPRESA 
			from TESTE..EMPRESA
			WHERE REPLACE(REPLACE(REPLACE(REPLACE(CGC, '.', ''), '/', ''), '/', ''), '-', '')  = @CGC_EMP

			PRINT 'ID_EMPRESA = '+CONVERT(VARCHAR(100), @ID_EMPRESA)

			--PEGA O PROXIMO ID
			select @ID_MOV_MAT = max(ID_MOV_MAT)+1 
			from TESTE..MOV_MAT

			PRINT 'ID_MOV_MAT = '+CONVERT(VARCHAR(100), @ID_MOV_MAT)

			-- INSERE O MOVIMENTO
			insert into TESTE..MOV_MAT
			  (ID_MOV_MAT /*MAX + 1*/, ID_MATERIAL, DATA, QTD, TP_MOV /*Tabela TP_MOV campo ID_TP_MOV (35)*/, VLR_UN, DOC, MOVIMENTO /*Tabela TP_MOV campo OPERACAO (1)*/, ID_EMPRESA, ID_FORNEC, LOTE, ID_NOTA_COMPRA /**/)
			values
			  (@ID_MOV_MAT, @ID_MATERIAL, @DATA, @QTD, 35, @VLR_UN, @DOC, 1, @ID_EMPRESA, @ID_FORNEC, @D1_LOTEFOR, @ID_NOTA_COMPRA)
		END

	COMMIT

End