USE [TOTVS12_PROD_R25]
GO
/****** Object:  StoredProcedure [dbo].[SP_MOV_GESTOQ_ESTORNO]    Script Date: 15/02/2021 16:51:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[SP_MOV_GESTOQ_ESTORNO]( 
	@AMBPROD		AS SMALLINT,
	@ID_MOV_MAT_ORI	AS INT,
	@ID_MOV_MAT		AS INT OUT
)
As
Begin
DECLARE @QTD AS INT

--ABRE TRANSAÇÃO
BEGIN TRAN

	IF @AMBPROD = 1
	BEGIN
		print 'AMBIENTE DE PRODUCAO'
		select @ID_MOV_MAT = max(ID_MOV_MAT)+1 
		from TPCP..MOV_MAT

		PRINT 'ID_MOV_MAT = '+CONVERT(VARCHAR(100), @ID_MOV_MAT)

		SELECT @QTD = COUNT(1)
		FROM TPCP..MOV_MAT
		WHERE ID_MOV_MAT = @ID_MOV_MAT_ORI

		IF @QTD > 0
		BEGIN
			-- INSERE O MOVIMENTO
			insert into TPCP..MOV_MAT
			(ID_MOV_MAT, ID_MATERIAL, DATA, QTD, TP_MOV, VLR_UN, DOC, MOVIMENTO, ID_EMPRESA, ID_FORNEC, LOTE)
			SELECT @ID_MOV_MAT, ID_MATERIAL, DATA, QTD, 105, VLR_UN, DOC, 0, ID_EMPRESA, ID_FORNEC, '' 
			FROM TPCP..MOV_MAT
			WHERE ID_MOV_MAT = @ID_MOV_MAT_ORI
		END
	END
	ELSE
	BEGIN
		print 'AMBIENTE DE TESTES'
		select @ID_MOV_MAT = max(ID_MOV_MAT)+1 
		from TESTE..MOV_MAT

		PRINT 'ID_MOV_MAT = '+CONVERT(VARCHAR(100), @ID_MOV_MAT)

		SELECT @QTD = COUNT(1)
		FROM TESTE..MOV_MAT
		WHERE ID_MOV_MAT = @ID_MOV_MAT_ORI
		
		IF @QTD > 0
		BEGIN
			-- INSERE O MOVIMENTO
			insert into TESTE..MOV_MAT
			  (ID_MOV_MAT, ID_MATERIAL, DATA, QTD, TP_MOV, VLR_UN, DOC, MOVIMENTO, ID_EMPRESA, ID_FORNEC, LOTE /**/)
			SELECT @ID_MOV_MAT, ID_MATERIAL, DATA, QTD, 105, VLR_UN, DOC, 0, ID_EMPRESA, ID_FORNEC, '' 
			FROM TESTE..MOV_MAT
			WHERE ID_MOV_MAT = @ID_MOV_MAT_ORI
		END
	END

--CONFIRMA A TRANSAÇÃO
COMMIT
END
