#INCLUDE "rwmake.ch"
/*
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณGAT002    บ Autor ณ AP6 IDE            บ Data ณ  07/12/05   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDescricao ณ Codigo gerado pelo AP6 IDE.                                บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP6 IDE                                                    บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
*/
User Function Gat002()

Local _aArea := GetArea()
Local _nVend := ""

IF funname() $ "CNTA120"                    
   RETURN(_nVend)
ENDIF

dbSelectArea("SA3")
dbSetOrder(1)
dbSeek(xFilial()+SA1->A1_VEND)
                                           
_nVend := SA3->A3_NOME

RestArea(_aArea)
Return (_nVend)
