-- Estoque -> Relatórios -> Específicos -> “Analise Conta Déb e Cré”

select SUBSTRING(CT2_DATA,7,2)+'/'+SUBSTRING(CT2_DATA,5,2)+'/'+SUBSTRING(CT2_DATA,1,4) 

AS CT2_DATA,

CT2_DEBITO,DEB1.CT1_DESC01,CT2_CREDIT,CRED1.CT1_DESC01,

CT2_CCD,DEB.CTT_DESC01,

CT2_HIST,

CT2_VALOR

from CT2010 CT2

INNER JOIN CT1010 DEB1 ON CT2_DEBITO = DEB1.CT1_CONTA AND DEB1.D_E_L_E_T_<> '*'

INNER JOIN CT1010 CRED1 ON CT2_CREDIT = CRED1.CT1_CONTA AND CRED1.D_E_L_E_T_<> '*'

LEFT JOIN CTT010 DEB ON CT2_CCD = CTT_CUSTO AND DEB.D_E_L_E_T_<> '*'

WHERE

CT2_DATA BETWEEN {MV_PAR01} AND {MV_PAR02} AND CT2.D_E_L_E_T_<>'*'

UNION ALL

select SUBSTRING(CT2_DATA,7,2)+'/'+SUBSTRING(CT2_DATA,5,2)+'/'+SUBSTRING(CT2_DATA,1,4) 

AS CT2_DATA, CT2_DEBITO,DEB1.CT1_DESC01,CT2_CREDIT,CRED1.CT1_DESC01,

CT2_CCC,CRED.CTT_DESC01,

CT2_HIST,

(CT2_VALOR*-1) AS CT2_VALOR

from CT2010 CT2

INNER JOIN CT1010 DEB1 ON CT2_DEBITO = DEB1.CT1_CONTA AND DEB1.D_E_L_E_T_<> '*'

INNER JOIN CT1010 CRED1 ON CT2_CREDIT = CRED1.CT1_CONTA AND CRED1.D_E_L_E_T_<> '*'

LEFT JOIN CTT010 CRED ON CT2_CCC = CRED.CTT_CUSTO AND CRED.D_E_L_E_T_<> '*'

WHERE

CT2_DATA BETWEEN {MV_PAR01} AND {MV_PAR02} AND CT2.D_E_L_E_T_<>'*'





-- Estoque -> Relatórios -> Específicos -> “Analise Full D3”

SELECT D3_OP,D3_TM, D3_COD, B1_DESC, D3_QUANT,D3_CF,D3_LOCAL,D3_TIPO, D3_XTIPO, D3_CUSTO1,D3_DOC,

SUBSTRING(D3_EMISSAO,7,2)+'/'+SUBSTRING(D3_EMISSAO,5,2)+'/'+SUBSTRING(D3_EMISSAO,1,4)  AS

DTEMISS, D3_QUANT,D3_CF,D3_LOCAL,D3_TIPO, D3_XTIPO, D3_CUSTO1,D3_LOTECTL,

CASE WHEN D3_CF IN ('DE4','RE4') THEN 'TRF'  

     WHEN D3_CF IN ('RE1','RE2') THEN 'PRD'

     WHEN D3_CF IN ('DE0') THEN 'GAN'

     WHEN D3_CF IN ('RE0') THEN 'PER'

     ELSE 'FALSO'

     END+'-'+TRIM(D3_CF)+'-'+TRIM(D3_TIPO)+'-'+TRIM(D3_XTIPO)+'-'+TRIM(D3_LOCAL) AS CHAVE

FROM SD3010 D3

INNER JOIN SB1010 B1 ON B1_COD =  D3_COD

WHERE


B1.D_E_L_E_T_<> '*' AND

D3.D_E_L_E_T_<> '*' AND

D3_EMISSAO BETWEEN {MV_PAR01} AND {MV_PAR02}



ESPZYN02



--Estoque -> Relatórios -> Específicos -> “Analise FullData CT2”

SELECT 'CTB'AS TP, CT2_DEBITO, CT2_CREDIT, CT2_CCD, CT2_CCC, TRIM (CT2_HIST) AS CHAVE,

CT2_VALOR AS VALOR FROM CT2010 CT

WHERE

D_E_L_E_T_<> '*' AND

CT2_LOTE = '008840' AND

CT2_DATA BETWEEN '20220801' AND '20220831'






--Estoque -> Relatórios -> Específicos -> “Analise Perda e Ganho”

SELECT * FROM (

SELECT D3_OP,D3_TM, D3_COD, D3_QUANT,D3_CF,D3_LOCAL,D3_TIPO, D3_XTIPO, D3_CUSTO1,

CASE WHEN D3_CF IN ('DE4','RE4') THEN 'TRF'  

     WHEN D3_CF IN ('RE1','RE2') THEN 'PRD'

     WHEN D3_CF IN ('DE0') THEN 'GAN'

     WHEN D3_CF IN ('RE0') THEN 'PER'

     ELSE 'FALSO'

     END+'-'+TRIM(D3_CF)+'-'+TRIM(D3_TIPO)+'-'+TRIM(D3_XTIPO)+'-'+TRIM(D3_LOCAL) AS CHAVE,

D3_USUARIO

FROM SD3010

WHERE

D_E_L_E_T_<> '*' AND

D3_EMISSAO BETWEEN {MV_PAR01} AND {MV_PAR02} AS TEMP

WHERE

TEMP.D3_CF = 'DE0'

UNION ALL

SELECT * FROM (

SELECT D3_OP,D3_TM, D3_COD, D3_QUANT,D3_CF,D3_LOCAL,D3_TIPO, D3_XTIPO, (D3_CUSTO1)*-1 AS

D3_CUSTO1,

CASE WHEN D3_CF IN ('DE4','RE4') THEN 'TRF'  

     WHEN D3_CF IN ('RE1','RE2') THEN 'PRD'

     WHEN D3_CF IN ('DE0') THEN 'GAN'

     WHEN D3_CF IN ('RE0') THEN 'PER'

     ELSE 'FALSO'

     END+'-'+TRIM(D3_CF)+'-'+TRIM(D3_TIPO)+'-'+TRIM(D3_XTIPO)+'-'+TRIM(D3_LOCAL) AS CHAVE,

D3_USUARIO

FROM SD3010

WHERE

D_E_L_E_T_<> '*' AND

D3_EMISSAO BETWEEN '20220801' AND '20220831') AS TEMP2

WHERE

TEMP2.D3_CF = 'RE0'

--Estoque -> Relatórios -> Específicos -> “Analise Reprocesso”



SELECT * FROM (

SELECT D3_OP,D3_TM, D3_COD, D3_QUANT,D3_CF,D3_LOCAL,D3_TIPO, D3_XTIPO, D3_CUSTO1/D3_QUANT

as custo,D3_CUSTO1,

CASE WHEN D3_CF IN ('DE4','RE4') THEN 'TRF'  

     WHEN D3_CF IN ('RE1','RE2') THEN 'PRD'

     WHEN D3_CF IN ('DE0') THEN 'GAN'

     WHEN D3_CF IN ('RE0') THEN 'PER'

     ELSE 'FALSO'

     END+'-'+TRIM(D3_CF)+'-'+TRIM(D3_TIPO)+'-'+TRIM(D3_XTIPO)+'-'+TRIM(D3_LOCAL) AS CHAVE

FROM SD3010

WHERE

D_E_L_E_T_<> '*' AND

D3_EMISSAO BETWEEN  '20220801' AND '20220831') AS TEMP

WHERE

TEMP.D3_CF = 'RE1' AND

TEMP.D3_COD LIKE '%R'

order by custo

--Estoque -> Relatórios -> Específicos -> “Analise D3 x CT2”

SELECT 'CTB'AS TP, TRIM(CT2_HIST) AS CHAVE, SUM(CT2_VALOR) AS VALOR FROM CT2010 CT

WHERE

D_E_L_E_T_<> '*' AND

CT2_LOTE = '008840' AND

CT2_DATA BETWEEN '20220801' AND '20220831' AND

CT2_HIST NOT LIKE 'CPV%' AND

CT2_HIST NOT LIKE 'CAM%' AND

CT2_HIST NOT LIKE 'CDV%' AND

CT2_HIST NOT LIKE 'CTR%' AND

CT2_HIST NOT LIKE 'CVD%'

GROUP BY

CT2_HIST

UNION ALL

SELECT 'D3' AS TP, TEMP.CHAVE, SUM(TEMP.D3_CUSTO1) AS VALOR FROM(

SELECT D3_OP,D3_TM, D3_COD, D3_QUANT,D3_CF,D3_LOCAL,D3_TIPO, D3_XTIPO, D3_CUSTO1,

CASE WHEN D3_CF IN ('DE4','RE4') THEN 'TRF'  

     WHEN D3_CF IN ('RE1','RE2') THEN 'PRD'

     WHEN D3_CF IN ('DE0') THEN 'GAN'

     WHEN D3_CF IN ('RE0') THEN 'PER'

     ELSE 'FALSO'

     END+'-'+TRIM(D3_CF)+'-'+TRIM(D3_TIPO)+'-'+TRIM(D3_XTIPO)+'-'+TRIM(D3_LOCAL) AS CHAVE

FROM SD3010

WHERE

D_E_L_E_T_<> '*' AND

D3_EMISSAO BETWEEN  '20220801' AND '20220831' ) AS TEMP

GROUP BY

TEMP.CHAVE

ORDER BY

CHAVE,TP

