SELECT G1_COD 'PRODUTO',
(SELECT B1_DESC FROM SB1010 SB1 WHERE B1_COD = G1_COD AND SB1.D_E_L_E_T_='') 'DESCPRODUTO',
G1_COMP 'COMPONENTE',
(SELECT B1_DESC FROM SB1010 SB1 WHERE B1_COD = G1_COMP AND SB1.D_E_L_E_T_='') 'DESCCOMPON',
G1_QUANT 'QUANTIDADE'
FROM SG1010 SG1
WHERE SG1.D_E_L_E_T_ = ''
ORDER BY G1_COD, G1_COMP