#Include 'Protheus.ch'

//---------------------------------------------------------------------------------
// Rotina | FISTRFNFE        | Autor | Lucas Baia          | Data |    06/04/2022	
//---------------------------------------------------------------------------------
// Descr. | Ponto de Entrada para manipular Menus da Rotina SPEDNFE.
//---------------------------------------------------------------------------------
// Uso    | DAREZ ATIVIDADES DE INTERNET E COMERCIO DE ACESSORIOS LTDA
//---------------------------------------------------------------------------------


User Function FISTRFNFE()

Local aArea := GetArea()
     
//Adicionando função de vincular
aadd(aRotina,{"Rel. Inutili/Cancela.","U_RNFCANC()", 0 , 3, 0 , Nil})
      
RestArea(aArea)

Return
